services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn campaign.app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 